export const OPPONENT_DETAILS = "OPPONENT_DETAILS";
export const UPDATE_SCORE = "UPDATE_SCORE";
export const PALYER_WALLET_ADDRESS = "PALYER_WALLET_ADDRESS";
export const PLAYER_BET_AMMOUNT = "PALYER_BET_AMMOUNT";
export const SOCKET_IO = "SOCKET_IO";
export const DIFFICULTY_LEVEL = "DIFFICULTY_LEVEL";
export const UPDATE_WINNER = "UPDATE_WINNER";
export const GAME_RENDER = "GAME_RENDER";
